version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/go/src/github.com/herdius/herdius-core
    overwrite: true
permissions:
  - object: /home/ec2-user/go/src/github.com/herdius/herdius-core/deployments/
    mode: 755
hooks:
  BeforeInstall:
    - location: deployment/kill_old_server.sh
      timeout: 10
      runas: root
  AfterInstall:
     - location: deployment/start_server.sh
       timeout: 60
       runas: ec2-user
