[dev]
selfbroadcastip = "127.0.0.1"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
syncdbpath = "./herdius/syncdb"
badgerdb = "badger"
leveldb = "goleveldb"
nodekeydir = "./supervisor/testdata/"
ethrpc = "https://ropsten.infura.io/v3/"
blockchaininforpc = "https://blockchain.info/rawaddr/"
hercontractaddress = "0x7562157d0bbb6d78935133bf06ae279e707aa9ad"
s3backupbucket = "herdius-blockchain-backup-dev"

[staging]
selfbroadcastip = "10.0.1.159"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
syncdbpath = "./herdius/syncdb"
badgerdb = "badger"
leveldb = "goleveldb"
nodekeydir = "./supervisor/testdata/"
blockchaininforpc = "https://blockchain.info/q"
ethrpc = "https://ropsten.infura.io/v3/"
s3backupbucket = "herdius-blockchain-backup-staging"


[prod]
selfbroadcastip = "not supported"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
syncdbpath = "./herdius/syncdb"
statedbpath = "./herdius/statedb"
badgerdb = "badger"
leveldb = "goleveldb"
ethrpc = "https://mainnet.infura.io/v3/"
blockchaininforpc = "https://blockchain.info/q"
s3backupbucket = "herdius-blockchain-backup-prod"