[dev]
selfbroadcastip = "127.0.0.1"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
badgerdb = "badger"
leveldb = "goleveldb"
nodekeydir = "./supervisor/testdata/"
ethrpc = "https://ropsten.infura.io"
hercontractaddress = "0xbd66049c525af5852cbc31eb25e29e54e82b2b66"


[staging]
selfbroadcastip = "10.0.1.159"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
badgerdb = "badger"
leveldb = "goleveldb"
nodekeydir = "./supervisor/testdata/"
ethrpc = "https://ropsten.infura.io"


[prod]
selfbroadcastip = "not supported"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
badgerdb = "badger"
leveldb = "goleveldb"
ethrpc = "https://ropsten.infura.io"

