[dev]
selfbroadcastip = "121.0.0.1"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
badgerdb = "badger"
leveldb = "goleveldb"
nodekeydir = "./supervisor/testdata/"

[staging]
selfbroadcastip = "10.0.1.159"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
badgerdb = "badger"
leveldb = "goleveldb"
nodekeydir = "./supervisor/testdata/"

[prod]
selfbroadcastip = "not supported"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
badgerdb = "badger"
leveldb = "goleveldb"
