[dev]
selfbroadcastip = "127.0.0.1"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
badgerdb = "badger"
leveldb = "goleveldb"
nodekeydir = "./supervisor/testdata/"
ethrpc = "https://ropsten.infura.io"
hercontractaddress = "0xfe3ff5ceee9ece33923e77b68dced3c781910f3a"


[staging]
selfbroadcastip = "10.0.1.159"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
badgerdb = "badger"
leveldb = "goleveldb"
nodekeydir = "./supervisor/testdata/"
ethrpc = "https://ropsten.infura.io"


[prod]
selfbroadcastip = "not supported"
selfbroadcastport = 3000
protocol = "tcp"
chaindbpath = "./herdius/chaindb"
statedbpath = "./herdius/statedb"
badgerdb = "badger"
leveldb = "goleveldb"
ethrpc = "https://ropsten.infura.io"

